spring:
  application:
    name: ModelMaestro
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/modelmaestro}
    username: ${DATABASE_USERNAME:modelmaestro}
    password: ${DATABASE_PASSWORD:modelmaestro}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: ${SERVER_PORT:8080}

